/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package me.fero.dictator;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        Dictator classUnderTest = new Dictator();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
